version: '3'
services:
  influx:
    image: influxdb
    container_name: influxdb
    environment:
      INFLUXDB_DB: test
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - "8086:8086"
    links:
      - backend
  backend:
    container_name: order-app
    image: order-app
    build: .
    ports:
      - "8080:8080"
