version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=abc_XYZ123
     - MYSQL_DATABASE=order_db
    ports:
      - "5432:5432"
  backend:
    container_name: order-app
    image: order_app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/order_db
    depends_on:
      - mysql
