version: '3'
services:
  influx:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: test
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - "8086:8086"
      - "8087:8082"
    volumes:
      - /tmp/influxdb:/var/lib/influxdb
  backend:
    container_name: order-app
    image: order-app
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - influx
